-
  name: 主機環境設定
  hosts: all
  become: False
  vars:
    deploy_account: deploy
    ruby_version: 2.6.4

  roles: 
    - user_settings
    - build_dependencies
    - install_apps
    # - ruby-install
    # - rvm
  tasks:
    # - name: 安裝 RVM part 1
    #   command: gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

    # - name: 安裝 RVM part 2
    #   command: "curl -sSL https://get.rvm.io | bash -s stable"
    #   become_method: sudo

    # - name: 安裝 RVM part 2
    #   command: rvm install {{ ruby_version }}

