-
  name: This is a test
  hosts: all
  vars:
    packages:
      - name: vim
        require: True
      - name: zsh
        require: True
      - name: postgresql
        require: True

  tasks: 
    - name: create account for deployment
      user: 
        name: deploy 
        state: present

    - name: set authorized key for user
      authorized_key:
        user: deploy
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Install required apps with deploy account
      apt:
        name: "{{ item.name }}"
        state: present
      loop: "{{ packages }}"
      become: true
      become_user: deploy
      become_method: su

