- name: 主機環境設定(Ubuntu 18.04)
  hosts: local_ubuntu_18
  become: no

  vars:
    deploy_account: deploy
    ruby_version: 2.6.5
    rails_version: 6.0.1

  roles: 
    - user_settings
    - prerequisite
    - build_dependencies
    - install_apps
    - { 
        role: rvm.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-{{ ruby_version }}'], 
        rvm1_install_flags: '--auto-dotfiles',
        become: yes, 
        rvm1_user: "{{ deploy_account }}" 
      }
    - gems
    - { 
        role: geerlingguy.passenger,
        tags: ruby,
        passenger_app_root: /var/www/public, 
        passenger_app_env: production, 
        passenger_ruby: "/home/{{ deploy_account }}/.rvm/rubies/ruby-{{ruby_version}}/bin/ruby"
      }
  tasks:

