- name: 新增佈署專用帳號 
  user: 
    name: "{{ deploy_account }}"
    shell: /bin/bash
    state: present

- name: 設定 sudo 指令權限
  become: true
  lineinfile:
    path: /etc/sudoers.d/{{ deploy_account }}
    line: "{{ deploy_account }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: 0440
    create: yes
    validate: "visudo -cf %s"

- name: 設定 SSH key
  authorized_key:
    user: "{{ deploy_account }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

