- name: 下載 ruby-install
  get_url:
    url: https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz
    dest: /home/{{ deploy_account }}/ruby-install.tar.gz
  become_method: sudo

- name: 解壓縮
  unarchive:
    src: /home/{{ deploy_account }}/ruby-install.tar.gz
    dest: /home/{{ deploy_account }}
    remote_src: yes
  become_method: sudo

- name: 安裝 ruby-install
  make:
    chdir: /home/{{ deploy_account }}/ruby-install-0.7.0
    target: install
  become_method: sudo

- name: 安裝 Ruby
  become_user: deploy
  command: /usr/local/bin/ruby-install --no-install-deps ruby {{ ruby_version }}
  args:
    creates: /home/{{ deploy_account }}/.rubies/ruby-{{ ruby_version }}
  become_method: sudo
